#[cfg(not(target_arch = "wasm32"))]
pub mod api;
pub mod app;
pub mod compat;
pub mod config;
pub mod constants;
pub mod custom;
#[cfg(not(target_arch = "wasm32"))]
pub mod event;
pub mod handler;
pub mod input;
pub mod interpretator;
pub mod logger;
pub mod mock;
pub mod modbus;
pub mod num_ops;
pub mod register;
pub mod state;
pub mod tui;
pub mod writes_log;
